=== EmilSoderlind/5DV135/Project/classes/artifacts/Apjava_Projekt_mby_jar/levels_/levels_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- List with levels in levelsType -->
    <xs:complexType name="mapsType">
        <xs:choice>
            <xs:element name="map" type="mapType" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:element name="maps" type="mapsType"/>

    <!--define level type -->
    <xs:complexType name="mapType">
        <xs:choice minOccurs="4" maxOccurs="unbounded">
            <xs:element name="tile" type="tileType" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="row" type="xs:integer" use="required"/>
        <xs:attribute name="col" type="xs:integer" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:element name="map" type="mapType"/>

    <!--tiles shares the same attributes -->
    <xs:complexType name="tileType">
        <xs:attribute name="x" type="xs:integer" use="required"/>
        <xs:attribute name="y" type="xs:integer" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="status" type="status" use="required"/>
    </xs:complexType>

    <!-- Requires a valid status -->
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:enumeration value="WALKABLE"/>
            <xs:enumeration value="GOAL"/>
            <xs:enumeration value="START"/>
            <xs:enumeration value="NONWALKABLE"/>
        </xs:restriction>
    </xs:simpleType>

    <!--define  all possible tiles-->
    <xs:element name="tile" type="tileType"/>
</xs:schema>

=== EmilSoderlind/5DV135/Project/classes/artifacts/Apjava_Projekt_mby_jar/levels_/test/levels_multiple_starts.xml
<?xml version="1.0" encoding="UTF-8"?>
<maps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../levels_schema.xsd">
    <map row="4" col="4" name="Karta 1!">
        <tile class="Model.Units.StartTile" x="0" y="0" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="1" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="2" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="1" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="2" y="3" status="WALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.GoalTile" x="3" y="3" status="GOAL"/>
    </map>
    <map row="4" col="4" name="Karta 2!"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../levels_schema.xsd">
        <tile class="Model.Units.StartTile" x="0" y="0" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="1" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="2" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="1" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="2" y="3" status="WALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.GoalTile" x="3" y="3" status="GOAL"/>
    </map>
</maps>

=== EmilSoderlind/5DV135/Project/classes/artifacts/Apjava_Projekt_mby_jar/levels_/levels.xml
<?xml version="1.0" encoding="UTF-8"?>
<maps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="levels_schema.xsd">
    <map row="5" col="5" name="Karta 4!">
        <tile x="0" y="0" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="0" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="0" class="Model.Units.StartTile" status="START"/>
        <tile x="3" y="0" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="4" y="0" class="Model.Units.BuildableTile" status="NONWALKABLE"/>

        <tile x="0" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="1" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="2" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="3" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="4" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="2" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="1" y="2" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="2" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="3" y="2" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="4" y="2" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="3" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="1" y="3" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="2" y="3" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="3" y="3" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="4" y="3" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="4" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="2" y="4" class="Model.Units.GoalTile" status="GOAL"/>
        <tile x="3" y="4" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="4" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
    </map>
    <map row="5" col="5" name="Karta 1!">
        <tile x="0" y="0" class="Model.Units.StartTile" status="START"/>
        <tile x="1" y="0" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="2" y="0" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="3" y="0" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="4" y="0" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="1" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="1" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="3" y="1" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="4" y="1" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="2" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="2" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="2" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="3" y="2" class="Model.Units.WalkableTile" status="WALKABLE"/>
        <tile x="4" y="2" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="3" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="3" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="3" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="3" y="3" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="4" y="3" class="Model.Units.WalkableTile" status="WALKABLE"/>

        <tile x="0" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="1" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="2" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="3" y="4" class="Model.Units.BuildableTile" status="NONWALKABLE"/>
        <tile x="4" y="4" class="Model.Units.GoalTile" status="GOAL"/>
    </map>
    <map row="4" col="4" name="Karta 2!">
        <tile class="Model.Units.StartTile" x="0" y="0" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="1" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="2" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="1" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="2" y="3" status="WALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.GoalTile" x="3" y="3" status="GOAL"/>
    </map>
    <map row="4" col="4" name="Karta 3!"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="levels_schema.xsd">
        <tile class="Model.Units.StartTile" x="0" y="0" status="START"/>
        <tile class="Model.Units.WalkableTile" x="0" y="1" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="2" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="0" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="1" y="3" status="WALKABLE"/>
        <tile class="Model.Units.WalkableTile" x="2" y="3" status="WALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="0" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="1" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="1" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="2" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.BuildableTile" x="3" y="2" status="NONWALKABLE"/>
        <tile class="Model.Units.GoalTile" x="3" y="3" status="GOAL"/>
    </map>
</maps>
